### ISSUE TITLE
The paper link

### ISSUE THREAD

**Issue by shaoyuyoung** [antonio-mastropaolo/SATD-Removal#1]
hi, antonio,

It seems that this is your new research, and I'm interested in it.

I wonder whether can you provide your original paper of this work.

Thx a lot :)
best regards.

**Comment by antonio-mastropaolo** [comment]
Hi @shaoyuyoung 

Thanks for your interest!
At the moment, I cannot provide you with the paper because it's still under review. Nonetheless, If it gets accepted, I will send the manuscript to you.

Have a nice day ;)
